name: werewolf
description: One night werewolf game.
# version: 1.0.0
# author: David J. H. Shih <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
